// <auto-generated />
using System;
using CodeFirstWithFluentApiCrudOperation.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeFirstWithFluentApiCrudOperation.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210206181739_CreateOneManyDepartmentEmpDep")]
    partial class CreateOneManyDepartmentEmpDep
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("CodeFirstWithFluentApiCrudOperation.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DepartmentID");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("CodeFirstWithFluentApiCrudOperation.Entities.Employee", b =>
                {
                    b.Property<int>("BusinessEntityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoginID")
                        .HasColumnType("int");

                    b.Property<int>("NationalIDNumber")
                        .HasColumnType("int");

                    b.Property<int>("OrganizationLevel")
                        .HasColumnType("int");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.HasKey("BusinessEntityID");

                    b.HasIndex("LoginID")
                        .IsUnique();

                    b.HasIndex("NationalIDNumber")
                        .IsUnique();

                    b.HasIndex("PersonID");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("CodeFirstWithFluentApiCrudOperation.Entities.EmployeeDepartmen", b =>
                {
                    b.Property<int>("ShiftID")
                        .HasColumnType("int");

                    b.Property<int>("BusinessEntityID")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndStateDocument")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDateDocument")
                        .HasColumnType("datetime2");

                    b.HasKey("ShiftID");

                    b.HasIndex("BusinessEntityID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("EmployeeDepartmen");
                });

            modelBuilder.Entity("CodeFirstWithFluentApiCrudOperation.Entities.EmployeePayHistory", b =>
                {
                    b.Property<int>("EmployeePayHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("BusinessEntityID")
                        .HasColumnType("int");

                    b.Property<int>("PayFrequency")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<DateTime>("RateChangeDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EmployeePayHistoryId");

                    b.HasIndex("BusinessEntityID")
                        .IsUnique();

                    b.HasIndex("RateChangeDate")
                        .IsUnique();

                    b.ToTable("EmployeePayHistory");
                });

            modelBuilder.Entity("CodeFirstWithFluentApiCrudOperation.Entities.JobCandidate", b =>
                {
                    b.Property<int>("JobCandidateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("BusinessEntityID")
                        .HasColumnType("int");

                    b.Property<string>("Resume")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobCandidateID");

                    b.HasIndex("BusinessEntityID");

                    b.ToTable("JobCandidate");
                });

            modelBuilder.Entity("CodeFirstWithFluentApiCrudOperation.Entities.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonID");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("CodeFirstWithFluentApiCrudOperation.Entities.SalesPerson", b =>
                {
                    b.Property<int>("SalesPersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("BusinessEntityID")
                        .HasColumnType("int");

                    b.Property<int>("SalesQuota")
                        .HasColumnType("int");

                    b.HasKey("SalesPersonID");

                    b.HasIndex("BusinessEntityID");

                    b.ToTable("SalesPerson");
                });

            modelBuilder.Entity("CodeFirstWithFluentApiCrudOperation.Entities.Shift", b =>
                {
                    b.Property<int>("ShiftID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ShiftID");

                    b.HasIndex("ShiftID")
                        .IsUnique();

                    b.ToTable("Shift");
                });

            modelBuilder.Entity("CodeFirstWithFluentApiCrudOperation.Entities.Employee", b =>
                {
                    b.HasOne("CodeFirstWithFluentApiCrudOperation.Entities.Person", "Person")
                        .WithMany("Employees")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CodeFirstWithFluentApiCrudOperation.Entities.EmployeeDepartmen", b =>
                {
                    b.HasOne("CodeFirstWithFluentApiCrudOperation.Entities.Employee", "Employee")
                        .WithMany("EmployeeDepartments")
                        .HasForeignKey("BusinessEntityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFirstWithFluentApiCrudOperation.Entities.Department", "Department")
                        .WithMany("EmployeeDepartments")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFirstWithFluentApiCrudOperation.Entities.Shift", "Shift")
                        .WithMany("EmployeeDepartments")
                        .HasForeignKey("ShiftID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Employee");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("CodeFirstWithFluentApiCrudOperation.Entities.EmployeePayHistory", b =>
                {
                    b.HasOne("CodeFirstWithFluentApiCrudOperation.Entities.Employee", "Employee")
                        .WithMany("EmployeePayHistories")
                        .HasForeignKey("BusinessEntityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CodeFirstWithFluentApiCrudOperation.Entities.JobCandidate", b =>
                {
                    b.HasOne("CodeFirstWithFluentApiCrudOperation.Entities.Employee", "Employee")
                        .WithMany("JobCandidates")
                        .HasForeignKey("BusinessEntityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CodeFirstWithFluentApiCrudOperation.Entities.SalesPerson", b =>
                {
                    b.HasOne("CodeFirstWithFluentApiCrudOperation.Entities.Employee", "Employee")
                        .WithMany("SalesPersons")
                        .HasForeignKey("BusinessEntityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CodeFirstWithFluentApiCrudOperation.Entities.Department", b =>
                {
                    b.Navigation("EmployeeDepartments");
                });

            modelBuilder.Entity("CodeFirstWithFluentApiCrudOperation.Entities.Employee", b =>
                {
                    b.Navigation("EmployeeDepartments");

                    b.Navigation("EmployeePayHistories");

                    b.Navigation("JobCandidates");

                    b.Navigation("SalesPersons");
                });

            modelBuilder.Entity("CodeFirstWithFluentApiCrudOperation.Entities.Person", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CodeFirstWithFluentApiCrudOperation.Entities.Shift", b =>
                {
                    b.Navigation("EmployeeDepartments");
                });
#pragma warning restore 612, 618
        }
    }
}
